owner: TriForMine
repo: isekaimaid-uptime

sites:
  - name: Isekai Maid
    url: https://www.isekaimaid.xyz
  - name: Isekai Maid Wiki
    url: https://wiki.isekaimaid.xyz
  - name: Isekai Maid Roadmap
    url: https://board.isekaimaid.xyz
  - name: Isekai Maid Bot
    check: "tcp-ping"
    url: server.isekaimaid.xyz
    port: 7777

assignees:
  - TriForMine

status-website:
  theme: dark
  cname: status.isekaimaid.xyz
  logoUrl: https://assets.isekaimaid.xyz/ms-icon-310x310.png
  name: Isekai Maid Status
  introTitle: "**Isekai Maid** is a Discord Bot with 40,000+ characters from all sorts of animes/mangas to claim, level up, trade, and more!"
  introMessage: On that page, you can see the uptime status of all the websites related to Isekai Maid.
  navbar:
    - title: Status
      href: /
    - title: Official Website
      href: https://www.isekaimaid.xyz
