# Change these first
owner: TriForMine # Your GitHub organization or username, where this repository lives
repo: isekaimaid-uptime # The name of this repository

sites:
  - name: Isekai Maid
    url: https://www.isekaimaid.xyz
  - name: Isekai Maid Wiki
    url: https://wiki.isekaimaid.xyz
  - name: Isekai Maid Roadmap
    url: https://board.isekaimaid.xyz

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.isekaimaid.xyz
  # baseUrl: /your-repo-name
  logoUrl: https://assets.isekaimaid.xyz/ms-icon-310x310.png
  name: Isekai Maid Status
  introTitle: "**Isekai Maid** is a Discord Bot with 40,000+ characters from all sorts of animes/mangas to claim, level up, trade, and more!"
  introMessage: On that page, you can see the uptime status of all the websites related to Isekai Maid.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
